"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-04 13:49:57.324305

"""
from collections.abc import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ── Integrity triggers (Postgres only; ADR-0003) ─────────────────────────────
TRIGGERS_UP = """
CREATE OR REPLACE FUNCTION forbid_event_mutation() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'events are append-only (ADR-0003)';
END $$ LANGUAGE plpgsql;
CREATE TRIGGER events_append_only BEFORE UPDATE OR DELETE ON events
  FOR EACH ROW EXECUTE FUNCTION forbid_event_mutation();

CREATE OR REPLACE FUNCTION guard_published_version() RETURNS trigger AS $$
BEGIN
  IF OLD.status IN ('published', 'superseded') THEN
    IF NEW.status = 'draft'
       OR NEW.number <> OLD.number
       OR NEW.plan_id <> OLD.plan_id
       OR NEW.kpis IS DISTINCT FROM OLD.kpis
       OR NEW.published_at IS DISTINCT FROM OLD.published_at THEN
      RAISE EXCEPTION 'published plan versions are immutable (BR-23)';
    END IF;
  END IF;
  RETURN NEW;
END $$ LANGUAGE plpgsql;
CREATE TRIGGER plan_versions_immutable BEFORE UPDATE ON plan_versions
  FOR EACH ROW EXECUTE FUNCTION guard_published_version();

CREATE OR REPLACE FUNCTION guard_published_trip() RETURNS trigger AS $$
DECLARE v_status text;
BEGIN
  SELECT status INTO v_status FROM plan_versions
   WHERE id = COALESCE(NEW.version_id, OLD.version_id);
  IF v_status IN ('published', 'superseded') THEN
    RAISE EXCEPTION 'trips of a published plan version are immutable (BR-23)';
  END IF;
  RETURN COALESCE(NEW, OLD);
END $$ LANGUAGE plpgsql;
CREATE TRIGGER trips_immutable BEFORE INSERT OR UPDATE OR DELETE ON trips
  FOR EACH ROW EXECUTE FUNCTION guard_published_trip();

-- Stops of a published version: only the operational status projection may change.
CREATE OR REPLACE FUNCTION guard_published_stop() RETURNS trigger AS $$
DECLARE v_status text;
BEGIN
  SELECT pv.status INTO v_status FROM trips t JOIN plan_versions pv ON pv.id = t.version_id
   WHERE t.id = COALESCE(NEW.trip_id, OLD.trip_id);
  IF v_status IN ('published', 'superseded') THEN
    IF TG_OP <> 'UPDATE'
       OR (to_jsonb(NEW) - 'status') IS DISTINCT FROM (to_jsonb(OLD) - 'status') THEN
      RAISE EXCEPTION 'stops of a published plan version are immutable (BR-23)';
    END IF;
  END IF;
  RETURN COALESCE(NEW, OLD);
END $$ LANGUAGE plpgsql;
CREATE TRIGGER stops_immutable BEFORE INSERT OR UPDATE OR DELETE ON stops
  FOR EACH ROW EXECUTE FUNCTION guard_published_stop();
"""

TRIGGERS_DOWN = """
DROP TRIGGER IF EXISTS stops_immutable ON stops;
DROP TRIGGER IF EXISTS trips_immutable ON trips;
DROP TRIGGER IF EXISTS plan_versions_immutable ON plan_versions;
DROP TRIGGER IF EXISTS events_append_only ON events;
DROP FUNCTION IF EXISTS guard_published_stop, guard_published_trip,
  guard_published_version, forbid_event_mutation;
"""


def _is_postgres() -> bool:
    return op.get_bind().dialect.name == "postgresql"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_days',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('dow', sa.Integer(), nullable=False),
    sa.Column('iso_year', sa.Integer(), nullable=False),
    sa.Column('iso_week', sa.Integer(), nullable=False),
    sa.Column('is_payday', sa.Boolean(), nullable=False),
    sa.Column('festival', sa.String(length=40), nullable=True),
    sa.Column('festival_ramp', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('is_holiday', sa.Boolean(), nullable=False),
    sa.Column('monsoon', sa.Boolean(), nullable=False),
    sa.Column('is_operating', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('date', name=op.f('pk_calendar_days'))
    )
    op.create_table('depots',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_depots'))
    )
    op.create_table('exceptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('shortfall', 'late_risk', 'pending_sync', 'store_report', 'conflict', 'fuel', name='exception_kind', native_enum=False), nullable=False),
    sa.Column('impact', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('suggested_fix', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', name='exception_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exceptions'))
    )
    op.create_table('products',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('brand', sa.Enum('Fresh', 'Style', 'Tech', name='brand', native_enum=False), nullable=False),
    sa.Column('is_chilled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_table('service_allowances',
    sa.Column('brand', sa.Enum('Fresh', 'Style', 'Tech', name='brand', native_enum=False), nullable=False),
    sa.Column('dock_type', sa.Enum('rear_dock', 'street', 'mall_bay', name='dock_type', native_enum=False), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('brand', 'dock_type', name=op.f('pk_service_allowances'))
    )
    op.create_table('districts',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('depot', sa.String(length=40), nullable=False),
    sa.Column('road_class', sa.String(length=20), nullable=False),
    sa.Column('free_flow_kmh', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('depot_to_district_km', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('depot_to_district_min', sa.Integer(), nullable=False),
    sa.Column('inter_stop_km', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('inter_stop_min', sa.Integer(), nullable=False),
    sa.Column('is_dead_zone', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['depot'], ['depots.name'], name=op.f('fk_districts_depot_depots')),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_districts'))
    )
    op.create_table('plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('depot', sa.String(length=40), nullable=False),
    sa.Column('operating_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['depot'], ['depots.name'], name=op.f('fk_plans_depot_depots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans')),
    sa.UniqueConstraint('depot', 'operating_date', name=op.f('uq_plans_depot'))
    )
    op.create_table('vehicles',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('type', sa.Enum('truck', 'van', name='vehicle_type', native_enum=False), nullable=False),
    sa.Column('temp', sa.Enum('reefer', 'ambient', name='vehicle_temp', native_enum=False), nullable=False),
    sa.Column('weight_cap_kg', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('volume_cap_m3', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('fuel_type', sa.String(length=20), nullable=False),
    sa.Column('km_per_l', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('weekly_fuel_quota_l', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('depot', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['depot'], ['depots.name'], name=op.f('fk_vehicles_depot_depots')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_vehicles'))
    )
    op.create_table('fuel_ledger',
    sa.Column('vehicle_code', sa.String(length=10), nullable=False),
    sa.Column('iso_year', sa.Integer(), nullable=False),
    sa.Column('iso_week', sa.Integer(), nullable=False),
    sa.Column('litres_used', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_code'], ['vehicles.code'], name=op.f('fk_fuel_ledger_vehicle_code_vehicles')),
    sa.PrimaryKeyConstraint('vehicle_code', 'iso_year', 'iso_week', name=op.f('pk_fuel_ledger'))
    )
    op.create_table('outlets',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('brand', sa.Enum('Fresh', 'Style', 'Tech', name='brand', native_enum=False), nullable=False),
    sa.Column('district', sa.String(length=40), nullable=False),
    sa.Column('depot', sa.String(length=40), nullable=False),
    sa.Column('dock_type', sa.Enum('rear_dock', 'street', 'mall_bay', name='dock_type', native_enum=False), nullable=False),
    sa.Column('parking_constraint', sa.Enum('normal', 'van_only', 'mall_dock', name='parking_constraint', native_enum=False), nullable=False),
    sa.Column('mall_window_open', sa.Time(), nullable=True),
    sa.Column('mall_window_close', sa.Time(), nullable=True),
    sa.Column('window_open', sa.Time(), nullable=False),
    sa.Column('window_close', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['depot'], ['depots.name'], name=op.f('fk_outlets_depot_depots')),
    sa.ForeignKeyConstraint(['district'], ['districts.name'], name=op.f('fk_outlets_district_districts')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_outlets'))
    )
    op.create_table('travel_ratios',
    sa.Column('district', sa.String(length=40), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('p50_ratio', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.Column('p90_ratio', sa.Numeric(precision=5, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['district'], ['districts.name'], name=op.f('fk_travel_ratios_district_districts')),
    sa.PrimaryKeyConstraint('district', 'hour', name=op.f('pk_travel_ratios'))
    )
    op.create_table('outlet_profiles',
    sa.Column('outlet_code', sa.String(length=10), nullable=False),
    sa.Column('split_rule', sa.Enum('same_morning_only', 'any', 'never', name='split_rule', native_enum=False), nullable=False),
    sa.Column('language', sa.Enum('si', 'ta', 'en', name='language', native_enum=False), nullable=False),
    sa.Column('contact_name', sa.String(length=80), nullable=True),
    sa.Column('access_note', sa.String(length=240), nullable=True),
    sa.ForeignKeyConstraint(['outlet_code'], ['outlets.code'], name=op.f('fk_outlet_profiles_outlet_code_outlets')),
    sa.PrimaryKeyConstraint('outlet_code', name=op.f('pk_outlet_profiles'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('role', sa.Enum('dispatcher', 'loader', 'driver', 'store_manager', name='role', native_enum=False), nullable=False),
    sa.Column('depot', sa.String(length=40), nullable=True),
    sa.Column('dock', sa.String(length=20), nullable=True),
    sa.Column('vehicle_code', sa.String(length=10), nullable=True),
    sa.Column('outlet_code', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['depot'], ['depots.name'], name=op.f('fk_users_depot_depots')),
    sa.ForeignKeyConstraint(['outlet_code'], ['outlets.code'], name=op.f('fk_users_outlet_code_outlets')),
    sa.ForeignKeyConstraint(['vehicle_code'], ['vehicles.code'], name=op.f('fk_users_vehicle_code_vehicles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('usual_quantities',
    sa.Column('outlet_code', sa.String(length=10), nullable=False),
    sa.Column('product_id', sa.String(length=40), nullable=False),
    sa.Column('usual_cases', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['outlet_code'], ['outlets.code'], name=op.f('fk_usual_quantities_outlet_code_outlets')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_usual_quantities_product_id_products')),
    sa.PrimaryKeyConstraint('outlet_code', 'product_id', name=op.f('pk_usual_quantities'))
    )
    op.create_table('clock_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demo_now', sa.DateTime(timezone=True), nullable=True),
    sa.Column('set_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('set_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['set_by'], ['users.id'], name=op.f('fk_clock_settings_set_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clock_settings'))
    )
    op.create_table('driver_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('outlet_code', sa.String(length=10), nullable=False),
    sa.Column('for_date', sa.Date(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('sent_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['outlet_code'], ['outlets.code'], name=op.f('fk_driver_notes_outlet_code_outlets')),
    sa.ForeignKeyConstraint(['sent_by'], ['users.id'], name=op.f('fk_driver_notes_sent_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_driver_notes'))
    )
    with op.batch_alter_table('driver_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_notes_outlet_code'), ['outlet_code'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ref', sa.String(length=20), nullable=False),
    sa.Column('outlet_code', sa.String(length=10), nullable=False),
    sa.Column('brand', sa.String(length=10), nullable=False),
    sa.Column('temp_requirement', sa.Enum('chilled', 'ambient', name='temp_requirement', native_enum=False), nullable=False),
    sa.Column('delivery_date', sa.Date(), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('volume_m3', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('deferred_yesterday', sa.Boolean(), nullable=False),
    sa.Column('days_since_last_served', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'placed', 'planned', 'deferred', 'loaded', 'in_transit', 'delivered', name='order_status', native_enum=False), nullable=False),
    sa.Column('source', sa.Enum('dataset', 'app', name='order_source', native_enum=False), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('placed_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['outlet_code'], ['outlets.code'], name=op.f('fk_orders_outlet_code_outlets')),
    sa.ForeignKeyConstraint(['placed_by'], ['users.id'], name=op.f('fk_orders_placed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_delivery_date'), ['delivery_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_outlet_code'), ['outlet_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_ref'), ['ref'], unique=True)

    op.create_table('plan_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'superseded', name='version_status', native_enum=False), nullable=False),
    sa.Column('parent_version_id', sa.Uuid(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('solver_status', sa.String(length=20), nullable=True),
    sa.Column('solve_ms', sa.Integer(), nullable=True),
    sa.Column('kpis', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('bottleneck', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_plan_versions_created_by_users')),
    sa.ForeignKeyConstraint(['parent_version_id'], ['plan_versions.id'], name=op.f('fk_plan_versions_parent_version_id_plan_versions')),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_plan_versions_plan_id_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_versions')),
    sa.UniqueConstraint('plan_id', 'number', name=op.f('uq_plan_versions_plan_id'))
    )
    with op.batch_alter_table('plan_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_versions_plan_id'), ['plan_id'], unique=False)

    op.create_table('vehicle_days',
    sa.Column('vehicle_code', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('available', 'in_workshop', name='vehicle_status', native_enum=False), nullable=False),
    sa.Column('switched_on', sa.Boolean(), nullable=False),
    sa.Column('off_reason', sa.String(length=120), nullable=True),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('fk_vehicle_days_changed_by_users')),
    sa.ForeignKeyConstraint(['vehicle_code'], ['vehicles.code'], name=op.f('fk_vehicle_days_vehicle_code_vehicles')),
    sa.PrimaryKeyConstraint('vehicle_code', 'date', name=op.f('pk_vehicle_days'))
    )
    op.create_table('deferrals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('reason_code', sa.Enum('NO_REEFER_CAPACITY', 'NO_VAN_AVAILABLE', 'VOLUME_CAP', 'WEIGHT_CAP', 'FRESH_TIME_BUDGET', 'DAY_TIME_BUDGET', 'TRIP_LIMIT', 'FUEL_QUOTA', 'VEHICLE_UNAVAILABLE', 'LOWER_PRIORITY', name='reason_code', native_enum=False), nullable=False),
    sa.Column('group', sa.Enum('unavoidable', 'choice', name='deferral_group', native_enum=False), nullable=False),
    sa.Column('priority', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('displaces', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('next_run', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.Uuid(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirm_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], name=op.f('fk_deferrals_confirmed_by_users')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_deferrals_order_id_orders')),
    sa.ForeignKeyConstraint(['version_id'], ['plan_versions.id'], name=op.f('fk_deferrals_version_id_plan_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deferrals')),
    sa.UniqueConstraint('version_id', 'order_id', name=op.f('uq_deferrals_version_id'))
    )
    with op.batch_alter_table('deferrals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deferrals_version_id'), ['version_id'], unique=False)

    op.create_table('events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.String(length=80), nullable=True),
    sa.Column('plan_version_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_events_actor_id_users')),
    sa.ForeignKeyConstraint(['plan_version_id'], ['plan_versions.id'], name=op.f('fk_events_plan_version_id_plan_versions')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_events'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('outlet_code', sa.String(length=10), nullable=True),
    sa.Column('recipient_user_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('deferral', 'eta_late', 'decision', 'plan_changed', name='notification_kind', native_enum=False), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('reason_code', sa.String(length=40), nullable=True),
    sa.Column('lang', sa.String(length=2), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_notifications_order_id_orders')),
    sa.ForeignKeyConstraint(['outlet_code'], ['outlets.code'], name=op.f('fk_notifications_outlet_code_outlets')),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], name=op.f('fk_notifications_recipient_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_outlet_code'), ['outlet_code'], unique=False)

    op.create_table('order_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.String(length=40), nullable=False),
    sa.Column('qty_ordered', sa.Integer(), nullable=False),
    sa.Column('qty_loaded', sa.Integer(), nullable=True),
    sa.Column('qty_delivered', sa.Integer(), nullable=True),
    sa.Column('qty_received', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_lines_order_id_orders')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_order_lines_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_lines'))
    )
    with op.batch_alter_table('order_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_lines_order_id'), ['order_id'], unique=False)

    op.create_table('plan_acks',
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_plan_acks_user_id_users')),
    sa.ForeignKeyConstraint(['version_id'], ['plan_versions.id'], name=op.f('fk_plan_acks_version_id_plan_versions')),
    sa.PrimaryKeyConstraint('version_id', 'user_id', name=op.f('pk_plan_acks'))
    )
    op.create_table('receipts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('confirmed_by', sa.Uuid(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_cases', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], name=op.f('fk_receipts_confirmed_by_users')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_receipts_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receipts')),
    sa.UniqueConstraint('order_id', name=op.f('uq_receipts_order_id'))
    )
    op.create_table('trips',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('vehicle_code', sa.String(length=10), nullable=False),
    sa.Column('trip_no', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=10), nullable=False),
    sa.Column('district', sa.String(length=40), nullable=False),
    sa.Column('lane', sa.Enum('predawn', 'daytime', name='trip_lane', native_enum=False), nullable=False),
    sa.Column('planned_depart', sa.Time(), nullable=True),
    sa.Column('plan_minutes', sa.Integer(), nullable=False),
    sa.Column('litres', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('volume_m3', sa.Numeric(precision=7, scale=3), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.CheckConstraint('trip_no IN (1, 2)', name=op.f('ck_trips_trip_no')),
    sa.ForeignKeyConstraint(['district'], ['districts.name'], name=op.f('fk_trips_district_districts')),
    sa.ForeignKeyConstraint(['vehicle_code'], ['vehicles.code'], name=op.f('fk_trips_vehicle_code_vehicles')),
    sa.ForeignKeyConstraint(['version_id'], ['plan_versions.id'], name=op.f('fk_trips_version_id_plan_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trips')),
    sa.UniqueConstraint('version_id', 'vehicle_code', 'trip_no', name=op.f('uq_trips_version_id'))
    )
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trips_version_id'), ['version_id'], unique=False)

    op.create_table('issues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('store_report', 'count_conflict', 'stale_plan', name='issue_kind', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', name='issue_status', native_enum=False), nullable=False),
    sa.Column('driver_event_id', sa.Uuid(), nullable=True),
    sa.Column('driver_qty', sa.Integer(), nullable=True),
    sa.Column('store_qty', sa.Integer(), nullable=True),
    sa.Column('store_photo_url', sa.String(length=300), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolution', sa.Enum('redeliver', 'credit', 'reject', 'driver_stands', 'store_stands', 'recount', name='issue_resolution', native_enum=False), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['driver_event_id'], ['events.event_id'], name=op.f('fk_issues_driver_event_id_events')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_issues_order_id_orders')),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_issues_resolved_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issues'))
    )
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issues_order_id'), ['order_id'], unique=False)

    op.create_table('receipt_lines',
    sa.Column('receipt_id', sa.Uuid(), nullable=False),
    sa.Column('order_line_id', sa.Uuid(), nullable=False),
    sa.Column('driver_qty', sa.Integer(), nullable=False),
    sa.Column('store_qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_lines.id'], name=op.f('fk_receipt_lines_order_line_id_order_lines')),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], name=op.f('fk_receipt_lines_receipt_id_receipts')),
    sa.PrimaryKeyConstraint('receipt_id', 'order_line_id', name=op.f('pk_receipt_lines'))
    )
    op.create_table('shortfalls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('missing', 'damaged', name='shortfall_kind', native_enum=False), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('short_from_chiller_pick', 'not_on_dock', 'damaged_in_pick', 'other', name='shortfall_reason', native_enum=False), nullable=False),
    sa.Column('photo_url', sa.String(length=300), nullable=True),
    sa.Column('reported_by', sa.Uuid(), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_shortfalls_order_id_orders')),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], name=op.f('fk_shortfalls_reported_by_users')),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_shortfalls_trip_id_trips')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shortfalls'))
    )
    with op.batch_alter_table('shortfalls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shortfalls_trip_id'), ['trip_id'], unique=False)

    op.create_table('stops',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('outlet_code', sa.String(length=10), nullable=False),
    sa.Column('plan_arrival', sa.Time(), nullable=True),
    sa.Column('likely_from', sa.Time(), nullable=True),
    sa.Column('likely_to', sa.Time(), nullable=True),
    sa.Column('at_risk', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['outlet_code'], ['outlets.code'], name=op.f('fk_stops_outlet_code_outlets')),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_stops_trip_id_trips')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stops')),
    sa.UniqueConstraint('trip_id', 'seq', name=op.f('uq_stops_trip_id'))
    )
    with op.batch_alter_table('stops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stops_trip_id'), ['trip_id'], unique=False)

    op.create_table('holds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trip_id', sa.Uuid(), nullable=False),
    sa.Column('shortfall_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('active', 'released', name='hold_status', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['released_by'], ['users.id'], name=op.f('fk_holds_released_by_users')),
    sa.ForeignKeyConstraint(['shortfall_id'], ['shortfalls.id'], name=op.f('fk_holds_shortfall_id_shortfalls')),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_holds_trip_id_trips')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holds'))
    )
    with op.batch_alter_table('holds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holds_trip_id'), ['trip_id'], unique=False)

    op.create_table('issue_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('issue_id', sa.Uuid(), nullable=False),
    sa.Column('order_line_id', sa.Uuid(), nullable=True),
    sa.Column('product_id', sa.String(length=40), nullable=True),
    sa.Column('problem', sa.Enum('missing', 'damaged', 'wrong_item', 'warm', name='line_problem', native_enum=False), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], name=op.f('fk_issue_lines_issue_id_issues')),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_lines.id'], name=op.f('fk_issue_lines_order_line_id_order_lines')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_issue_lines_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issue_lines'))
    )
    with op.batch_alter_table('issue_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issue_lines_issue_id'), ['issue_id'], unique=False)

    op.create_table('repair_options',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('shortfall_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=4), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('breaks_store_rule', sa.Boolean(), nullable=False),
    sa.Column('loss', sa.Numeric(precision=9, scale=2), nullable=False),
    sa.Column('recommended', sa.Boolean(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['applied_by'], ['users.id'], name=op.f('fk_repair_options_applied_by_users')),
    sa.ForeignKeyConstraint(['shortfall_id'], ['shortfalls.id'], name=op.f('fk_repair_options_shortfall_id_shortfalls')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_repair_options'))
    )
    with op.batch_alter_table('repair_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repair_options_shortfall_id'), ['shortfall_id'], unique=False)

    op.create_table('stop_orders',
    sa.Column('stop_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('planned_cases', sa.Integer(), nullable=False),
    sa.Column('top_up_of_order_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_stop_orders_order_id_orders')),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], name=op.f('fk_stop_orders_stop_id_stops')),
    sa.ForeignKeyConstraint(['top_up_of_order_id'], ['orders.id'], name=op.f('fk_stop_orders_top_up_of_order_id_orders')),
    sa.PrimaryKeyConstraint('stop_id', 'order_id', name=op.f('pk_stop_orders'))
    )
    # ### end Alembic commands ###
    if _is_postgres():
        op.execute(TRIGGERS_UP)


def downgrade() -> None:
    """Downgrade schema."""
    if _is_postgres():
        op.execute(TRIGGERS_DOWN)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stop_orders')
    with op.batch_alter_table('repair_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repair_options_shortfall_id'))

    op.drop_table('repair_options')
    with op.batch_alter_table('issue_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_lines_issue_id'))

    op.drop_table('issue_lines')
    with op.batch_alter_table('holds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holds_trip_id'))

    op.drop_table('holds')
    with op.batch_alter_table('stops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stops_trip_id'))

    op.drop_table('stops')
    with op.batch_alter_table('shortfalls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shortfalls_trip_id'))

    op.drop_table('shortfalls')
    op.drop_table('receipt_lines')
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issues_order_id'))

    op.drop_table('issues')
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trips_version_id'))

    op.drop_table('trips')
    op.drop_table('receipts')
    op.drop_table('plan_acks')
    with op.batch_alter_table('order_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_lines_order_id'))

    op.drop_table('order_lines')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_outlet_code'))

    op.drop_table('notifications')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_entity')

    op.drop_table('events')
    with op.batch_alter_table('deferrals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deferrals_version_id'))

    op.drop_table('deferrals')
    op.drop_table('vehicle_days')
    with op.batch_alter_table('plan_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_versions_plan_id'))

    op.drop_table('plan_versions')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_ref'))
        batch_op.drop_index(batch_op.f('ix_orders_outlet_code'))
        batch_op.drop_index(batch_op.f('ix_orders_delivery_date'))

    op.drop_table('orders')
    with op.batch_alter_table('driver_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_notes_outlet_code'))

    op.drop_table('driver_notes')
    op.drop_table('clock_settings')
    op.drop_table('usual_quantities')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('outlet_profiles')
    op.drop_table('travel_ratios')
    op.drop_table('outlets')
    op.drop_table('fuel_ledger')
    op.drop_table('vehicles')
    op.drop_table('plans')
    op.drop_table('districts')
    op.drop_table('service_allowances')
    op.drop_table('products')
    op.drop_table('exceptions')
    op.drop_table('depots')
    op.drop_table('calendar_days')
    # ### end Alembic commands ###
