/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Liveness probe */
    get: operations['health_api_v1_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Sign in (X1) */
    post: operations['login_api_v1_auth_login_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Current user and scope */
    get: operations['me_api_v1_auth_me_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/clock': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Current operating time */
    get: operations['read_clock_api_v1_clock_get']
    /** Set or clear the demo time (dispatcher) */
    put: operations['set_clock_api_v1_clock_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/stream': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Live updates (Server-Sent Events) */
    get: operations['stream_api_v1_stream_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/fleet': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Fleet */
    get: operations['get_fleet_api_v1_fleet_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/fleet/{vehicle}/{operating_date}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Switch */
    patch: operations['switch_api_v1_fleet__vehicle___operating_date__patch']
    trace?: never
  }
  '/api/v1/plans/{operating_date}/generate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Generate */
    post: operations['generate_api_v1_plans__operating_date__generate_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/plans/{operating_date}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Plan */
    get: operations['get_plan_api_v1_plans__operating_date__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/plan-versions/{version_id}/deferrals/confirm': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Confirm */
    post: operations['confirm_api_v1_plan_versions__version_id__deferrals_confirm_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/plan-versions/{version_id}/publish-check': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Publish Check */
    get: operations['publish_check_api_v1_plan_versions__version_id__publish_check_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/plan-versions/{version_id}/publish': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Publish */
    post: operations['publish_api_v1_plan_versions__version_id__publish_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/deferrals/{deferral_id}/serve-instead': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Serve Instead */
    post: operations['serve_instead_api_v1_deferrals__deferral_id__serve_instead_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/trips/{trip_id}/lock': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Lock Trip */
    post: operations['lock_trip_api_v1_trips__trip_id__lock_post']
    /** Unlock Trip */
    delete: operations['unlock_trip_api_v1_trips__trip_id__lock_delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/shortfalls/{shortfall_id}/options': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Options */
    get: operations['options_api_v1_shortfalls__shortfall_id__options_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/shortfalls/{shortfall_id}/apply': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Apply */
    post: operations['apply_api_v1_shortfalls__shortfall_id__apply_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/sync': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Sync
     * @description Apply a device outbox in order; idempotent by `event_id` (BR-35 to BR-37, BR-52, BR-53).
     */
    post: operations['sync_api_v1_sync_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/sync/bootstrap': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Bootstrap
     * @description Everything a field device needs to work offline today (docs/07 › Client side, BR-38).
     */
    get: operations['bootstrap_api_v1_sync_bootstrap_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/vehicles/{code}/today': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Vehicle Today
     * @description Published trips, stops, two clocks, notes and known shortfalls (BR-32 to BR-34, BR-39).
     */
    get: operations['vehicle_today_api_v1_vehicles__code__today_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** BootstrapOut */
    BootstrapOut: {
      /**
       * Server Time
       * Format: date-time
       */
      server_time: string
      /**
       * Operating Date
       * Format: date
       */
      operating_date: string
      user: components['schemas']['BootstrapUserOut']
      /** Vehicles */
      vehicles: components['schemas']['VehicleTodayOut'][]
    }
    /** BootstrapUserOut */
    BootstrapUserOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Name */
      name: string
      /** Role */
      role: string
      /** Depot */
      depot: string | null
      /** Dock */
      dock: string | null
      /** Vehicle Code */
      vehicle_code: string | null
    }
    /** BottleneckOut */
    BottleneckOut: {
      /** Resource */
      resource: string
      /** Used */
      used: number
      /** Capacity */
      capacity: number
      /** Explanation */
      explanation: string
    }
    /** ClockOut */
    ClockOut: {
      /**
       * Now
       * Format: date-time
       */
      now: string
      /** Is Demo */
      is_demo: boolean
    }
    /** ClockSet */
    ClockSet: {
      /** Demo Now */
      demo_now: string | null
    }
    /** ConfirmIn */
    ConfirmIn: {
      /** Items */
      items: components['schemas']['ConfirmItem'][]
    }
    /** ConfirmItem */
    ConfirmItem: {
      /**
       * Deferral Id
       * Format: uuid
       */
      deferral_id: string
      /** Reason */
      reason?: string | null
    }
    /** DeferralOut */
    DeferralOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Order Ref */
      order_ref: string
      /** Outlet Code */
      outlet_code: string
      /** Reason Code */
      reason_code: string
      /** Group */
      group: string
      /** Priority */
      priority: number
      /** Explanation */
      explanation: string | null
      /** Displaces */
      displaces: string[]
      /** Next Run */
      next_run: string | null
      /** Repeat Skip */
      repeat_skip: boolean
      /** Confirmed */
      confirmed: boolean
      /** Confirm Reason */
      confirm_reason: string | null
      /** District */
      district: string
      /** Temp Requirement */
      temp_requirement: string
      /** Volume M3 */
      volume_m3: number
      /** Weight Kg */
      weight_kg: number
      /**
       * Notice Body
       * @default
       */
      notice_body: string
      /**
       * Notice Language
       * @default en
       */
      notice_language: string
    }
    /** EntityRef */
    EntityRef: {
      /**
       * Type
       * @enum {string}
       */
      type: 'trip' | 'stop' | 'order'
      /** Id */
      id: string
    }
    /** FleetOut */
    FleetOut: {
      /** Vehicle Code */
      vehicle_code: string
      /**
       * Date
       * Format: date
       */
      date: string
      /** Type */
      type: string
      /** Temp */
      temp: string
      /** Status */
      status: string
      /** Switched On */
      switched_on: boolean
      /** Off Reason */
      off_reason: string | null
      /** Weight Cap Kg */
      weight_cap_kg: number
      /** Volume Cap M3 */
      volume_cap_m3: number
      /** Fuel Used L */
      fuel_used_l: number
      /** Fuel Remaining L */
      fuel_remaining_l: number
    }
    /** FleetSwitchIn */
    FleetSwitchIn: {
      /** Switched On */
      switched_on: boolean
      /** Off Reason */
      off_reason?: string | null
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /**
     * KnownShortfallOut
     * @description A loading shortfall already reported for this order: pre-filled and locked (BR-34).
     */
    KnownShortfallOut: {
      /**
       * Shortfall Id
       * Format: uuid
       */
      shortfall_id: string
      /** Kind */
      kind: string
      /** Qty */
      qty: number
      /** Reason */
      reason: string
    }
    /** KpisOut */
    KpisOut: {
      /** Orders Served */
      orders_served: number
      /** Chilled Served */
      chilled_served: number
      /** Stops At Risk */
      stops_at_risk: number
      /** Deferrals */
      deferrals: number
      /** Value Served */
      value_served: number
      /** Reefer M3 Used */
      reefer_m3_used: number
      /** Reefer M3 Total */
      reefer_m3_total: number
    }
    /** LoginRequest */
    LoginRequest: {
      /** Email */
      email: string
      /** Password */
      password: string
    }
    /** OrderLineView */
    OrderLineView: {
      /** Product Id */
      product_id: string
      /** Name */
      name: string
      /** Qty */
      qty: number
    }
    /** PlanOut */
    PlanOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * Plan Id
       * Format: uuid
       */
      plan_id: string
      /** Number */
      number: number
      /**
       * Operating Date
       * Format: date
       */
      operating_date: string
      /** Depot */
      depot: string
      /** Status */
      status: string
      /** Solver Status */
      solver_status: string | null
      /** Solve Ms */
      solve_ms: number | null
      kpis: components['schemas']['KpisOut']
      bottleneck: components['schemas']['BottleneckOut']
      /** Trips */
      trips: components['schemas']['TripOut'][]
      /** Deferrals */
      deferrals: components['schemas']['DeferralOut'][]
      /** Orders Total */
      orders_total: number
      /** Chilled Total */
      chilled_total: number
    }
    /** PublishCheckOut */
    PublishCheckOut: {
      /** Can Publish */
      can_publish: boolean
      /** Violations */
      violations: components['schemas']['ViolationOut'][]
      /** Unconfirmed Deferrals */
      unconfirmed_deferrals: string[]
      /** Late Risk Order Refs */
      late_risk_order_refs: string[]
    }
    /** PublishIn */
    PublishIn: {
      /**
       * Accept Late Risk
       * @default false
       */
      accept_late_risk: boolean
    }
    /** RepairApplyIn */
    RepairApplyIn: {
      /**
       * Option Id
       * Format: uuid
       */
      option_id: string
    }
    /** RepairOptionOut */
    RepairOptionOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Label */
      label: string
      /** Rank */
      rank: number
      /** Title */
      title: string
      /** Gets */
      gets: string
      /** Delay */
      delay: string
      /** Other Stops */
      other_stops: string
      /** Loss */
      loss: number
      /** Loss Label */
      loss_label: string
      /** Breaks Store Rule */
      breaks_store_rule: boolean
      /** Recommended */
      recommended: boolean
    }
    /** RepairStopOut */
    RepairStopOut: {
      /** Outlet Code */
      outlet_code: string
      /** Order Ref */
      order_ref: string
      /** Cases */
      cases: number
      /** Available Cases */
      available_cases: number
      /**
       * Window Open
       * Format: time
       */
      window_open: string
      /**
       * Window Close
       * Format: time
       */
      window_close: string
    }
    /** ServeInsteadIn */
    ServeInsteadIn: {
      /**
       * Confirm
       * @default false
       */
      confirm: boolean
    }
    /** ServeInsteadOut */
    ServeInsteadOut: {
      /** Order Ref */
      order_ref: string
      /** Displaces */
      displaces: string[]
      version?: components['schemas']['PlanOut'] | null
    }
    /** ShortfallOptionsOut */
    ShortfallOptionsOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * Version Id
       * Format: uuid
       */
      version_id: string
      /** Version Number */
      version_number: number
      /** Next Version Number */
      next_version_number: number
      /**
       * Operating Date
       * Format: date
       */
      operating_date: string
      /** Vehicle Code */
      vehicle_code: string
      /** Trip No */
      trip_no: number
      /** Depot */
      depot: string
      /** Dock */
      dock: string | null
      /**
       * Reported At
       * Format: time
       */
      reported_at: string
      /** Reporter */
      reporter: string
      /** Kind */
      kind: string
      /** Reason */
      reason: string
      /** Order Ref */
      order_ref: string
      /** Outlet Code */
      outlet_code: string
      /** District */
      district: string
      /** Temp Requirement */
      temp_requirement: string
      /** Planned Cases */
      planned_cases: number
      /** Missing Cases */
      missing_cases: number
      /** Waiting Seconds */
      waiting_seconds: number
      /** To Departure Minutes */
      to_departure_minutes: number
      /** Planned Depart */
      planned_depart: string | null
      /** Split Rule */
      split_rule: string
      /** Split Rule Text */
      split_rule_text: string
      /** Held */
      held: boolean
      /** Solve Ms */
      solve_ms: number
      /** Stops */
      stops: components['schemas']['RepairStopOut'][]
      /** Options */
      options: components['schemas']['RepairOptionOut'][]
    }
    /** StopOrderOut */
    StopOrderOut: {
      /** Order Ref */
      order_ref: string
      /** Cases */
      cases: number
      /** Top Up Of Order Ref */
      top_up_of_order_ref?: string | null
    }
    /** StopOrderView */
    StopOrderView: {
      /**
       * Order Id
       * Format: uuid
       */
      order_id: string
      /** Order Ref */
      order_ref: string
      /** Temp Requirement */
      temp_requirement: string
      /** Planned Cases */
      planned_cases: number
      /** Weight Kg */
      weight_kg: number
      /** Volume M3 */
      volume_m3: number
      /** Top Up Of Order Ref */
      top_up_of_order_ref?: string | null
      /** Lines */
      lines: components['schemas']['OrderLineView'][]
      known_shortfall?: components['schemas']['KnownShortfallOut'] | null
    }
    /** StopOut */
    StopOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Seq */
      seq: number
      /** Outlet Code */
      outlet_code: string
      /** Plan Arrival */
      plan_arrival: string | null
      /** Likely From */
      likely_from: string | null
      /** Likely To */
      likely_to: string | null
      /** At Risk */
      at_risk: boolean
      /** Status */
      status: string
      /** Orders */
      orders: components['schemas']['StopOrderOut'][]
    }
    /** StopView */
    StopView: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Seq */
      seq: number
      /** Outlet Code */
      outlet_code: string
      /** District */
      district: string
      /** Status */
      status: string
      /** Plan Arrival */
      plan_arrival: string | null
      /** Likely From */
      likely_from: string | null
      /** Likely To */
      likely_to: string | null
      /** At Risk */
      at_risk: boolean
      /**
       * Window Open
       * Format: time
       */
      window_open: string
      /**
       * Window Close
       * Format: time
       */
      window_close: string
      /** Dock Type */
      dock_type: string
      /** Parking Constraint */
      parking_constraint: string
      /** Mall Window Open */
      mall_window_open: string | null
      /** Mall Window Close */
      mall_window_close: string | null
      /** Access Note */
      access_note: string | null
      /** Contact Name */
      contact_name: string | null
      /** Store Note */
      store_note: string | null
      /** Store Note At */
      store_note_at: string | null
      /** Arrived At */
      arrived_at: string | null
      /** Outcome */
      outcome: string | null
      /** Orders */
      orders: components['schemas']['StopOrderView'][]
    }
    /** SyncEventIn */
    SyncEventIn: {
      /**
       * Event Id
       * Format: uuid
       */
      event_id: string
      /**
       * Type
       * @enum {string}
       */
      type:
        | 'trip_acknowledged'
        | 'load_checked'
        | 'trip_loaded'
        | 'shortfall_reported'
        | 'arrived'
        | 'outcome_recorded'
        | 'note_added'
      entity: components['schemas']['EntityRef']
      /** Plan Version Id */
      plan_version_id?: string | null
      /**
       * Event Time
       * Format: date-time
       */
      event_time: string
      /** Seq */
      seq?: number | null
      /** Payload */
      payload?: {
        [key: string]: unknown
      }
    }
    /** SyncIn */
    SyncIn: {
      /** Device Id */
      device_id: string
      /** Events */
      events: components['schemas']['SyncEventIn'][]
    }
    /** SyncOut */
    SyncOut: {
      /** Results */
      results: components['schemas']['SyncResultOut'][]
      /**
       * Server Time
       * Format: date-time
       */
      server_time: string
    }
    /** SyncResultOut */
    SyncResultOut: {
      /**
       * Event Id
       * Format: uuid
       */
      event_id: string
      /**
       * Status
       * @enum {string}
       */
      status: 'accepted' | 'duplicate' | 'conflict' | 'rejected'
      /** Conflict Id */
      conflict_id?: string | null
      /** Code */
      code?: string | null
      /** Rule Id */
      rule_id?: string | null
      /** Detail */
      detail?: string | null
      /** Driver Qty */
      driver_qty?: number | null
      /** Store Qty */
      store_qty?: number | null
      /** Store Time */
      store_time?: string | null
    }
    /** TokenOut */
    TokenOut: {
      /** Access Token */
      access_token: string
      /**
       * Token Type
       * @default bearer
       * @constant
       */
      token_type: 'bearer'
      /**
       * Expires In
       * @description seconds
       */
      expires_in: number
      user: components['schemas']['UserOut']
    }
    /** TripOut */
    TripOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Vehicle Code */
      vehicle_code: string
      /** Trip No */
      trip_no: number
      /** Brand */
      brand: string
      /** District */
      district: string
      /** Lane */
      lane: string
      /** Planned Depart */
      planned_depart: string | null
      /** Plan Minutes */
      plan_minutes: number
      /** Litres */
      litres: number
      /** Weight Kg */
      weight_kg: number
      /** Volume M3 */
      volume_m3: number
      /** Locked */
      locked: boolean
      /** Stops */
      stops: components['schemas']['StopOut'][]
      /** Rule Messages */
      rule_messages?: components['schemas']['ViolationOut'][]
      /** Protected Outlets */
      protected_outlets?: string[]
    }
    /** TripView */
    TripView: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Trip No */
      trip_no: number
      /** Lane */
      lane: string
      /** Brand */
      brand: string
      /** District */
      district: string
      /** Planned Depart */
      planned_depart: string | null
      /** Plan Minutes */
      plan_minutes: number
      /** Weight Kg */
      weight_kg: number
      /** Volume M3 */
      volume_m3: number
      /** On Hold */
      on_hold: boolean
      /** Hold Shortfall Id */
      hold_shortfall_id: string | null
      /** Stops */
      stops: components['schemas']['StopView'][]
    }
    /** UserOut */
    UserOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Email */
      email: string
      /** Name */
      name: string
      /**
       * Role
       * @enum {string}
       */
      role: 'dispatcher' | 'loader' | 'driver' | 'store_manager'
      /** Depot */
      depot: string | null
      /** Dock */
      dock: string | null
      /** Vehicle Code */
      vehicle_code: string | null
      /** Outlet Code */
      outlet_code: string | null
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
      /** Input */
      input?: unknown
      /** Context */
      ctx?: Record<string, never>
    }
    /** VehicleTodayOut */
    VehicleTodayOut: {
      /** Vehicle Code */
      vehicle_code: string
      /** Vehicle Type */
      vehicle_type: string
      /** Vehicle Temp */
      vehicle_temp: string
      /**
       * Operating Date
       * Format: date
       */
      operating_date: string
      /**
       * Server Time
       * Format: date-time
       */
      server_time: string
      version: components['schemas']['VersionView'] | null
      /** Trips */
      trips: components['schemas']['TripView'][]
    }
    /** VersionView */
    VersionView: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Number */
      number: number
      /** Published At */
      published_at: string | null
      /** Change Reason */
      change_reason: string | null
      /** Acknowledged */
      acknowledged: boolean
      /** Acked At */
      acked_at: string | null
    }
    /** ViolationOut */
    ViolationOut: {
      /** Rule Id */
      rule_id: string
      /** Code */
      code: string
      /** Message */
      message: string
      /** Context */
      context: {
        [key: string]: string | number | boolean | string[]
      }
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  health_api_v1_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            [key: string]: string
          }
        }
      }
    }
  }
  login_api_v1_auth_login_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TokenOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  me_api_v1_auth_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserOut']
        }
      }
    }
  }
  read_clock_api_v1_clock_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ClockOut']
        }
      }
    }
  }
  set_clock_api_v1_clock_put: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ClockSet']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ClockOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  stream_api_v1_stream_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  get_fleet_api_v1_fleet_get: {
    parameters: {
      query: {
        date: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FleetOut'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  switch_api_v1_fleet__vehicle___operating_date__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        vehicle: string
        operating_date: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['FleetSwitchIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['FleetOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  generate_api_v1_plans__operating_date__generate_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        operating_date: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PlanOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_plan_api_v1_plans__operating_date__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        operating_date: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PlanOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  confirm_api_v1_plan_versions__version_id__deferrals_confirm_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        version_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ConfirmIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PlanOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  publish_check_api_v1_plan_versions__version_id__publish_check_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        version_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PublishCheckOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  publish_api_v1_plan_versions__version_id__publish_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        version_id: string
      }
      cookie?: never
    }
    requestBody?: {
      content: {
        'application/json': components['schemas']['PublishIn'] | null
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PlanOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  serve_instead_api_v1_deferrals__deferral_id__serve_instead_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        deferral_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ServeInsteadIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ServeInsteadOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  lock_trip_api_v1_trips__trip_id__lock_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        trip_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PlanOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  unlock_trip_api_v1_trips__trip_id__lock_delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        trip_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PlanOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  options_api_v1_shortfalls__shortfall_id__options_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        shortfall_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ShortfallOptionsOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  apply_api_v1_shortfalls__shortfall_id__apply_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        shortfall_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['RepairApplyIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PlanOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  sync_api_v1_sync_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SyncIn']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SyncOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  bootstrap_api_v1_sync_bootstrap_get: {
    parameters: {
      query?: {
        date?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BootstrapOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  vehicle_today_api_v1_vehicles__code__today_get: {
    parameters: {
      query?: {
        date?: string | null
      }
      header?: never
      path: {
        code: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['VehicleTodayOut']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
